### ISSUE TITLE
Configuration option to disable logs in production

### ISSUE THREAD

**Issue by shihgianlee** [bentoml/BentoML#1009]
**Is your feature request related to a problem? Please describe.**
We have a mechanism to capture logs in production that doesn't require log files collection. However, there is no option to disable local log files generation.

**Describe the solution you'd like**
A configuration option for user to disable logging to files.

**Describe alternatives you've considered**
Accept the default behavior since log rotation is in place. There is no concerns that the log files will grow large and eat up disk space on the server.

**Comment by parano** [comment]
cc @bojiang as discussed - add the following CLI arg to bentoml API server: `--enable-log-to-file` / `BENTOML_ENABLE_LOG_TO_FILE=True`, default to `true`.

**Comment by ssheng** [comment]
I'm going take a stab at this problem next. Discussed offline with @yubozhao, we think the best option might to be generically expose the full logging configuration rather than just the log-to-file option, so we can hopefully solve all logging customization needs.

My plan is to expose the logging configuration through CLI param and environment variables in that priority order. Docker and K8s can hopefully leverage it without much change.

Please let me know your thoughts.

**Comment by yubozhao** [comment]
Thank you @ssheng for working on this issue.  I think this is a great addition to the community.

@shihgianlee This feature will be part of the next release.  Feel free to reopen this issue, if you have additional questions.
