### ISSUE TITLE
Add --with-docker argument for running BentoML inference job from CLI

### ISSUE THREAD

**Issue by parano** [bentoml/BentoML#1192]
**Is your feature request related to a problem? Please describe.**

When launching a batch inference job from CLI, it is quite common for users to ask BentoML to set up all the conda/PyPI dependencies automatically for the job.

In the older BentoML version, there's a `--with-conda` argument that does exactly this.  But we removed it in #898 due to its inconsistency with the docker environment and the service may be missing additional dependencies when only considering its conda and python dependencies.

Currently, a user will need to first build a docker container image and then launch the inference job with the docker image, here’s an example to run CLI predict with docker, using the quickstart guide example:

```bash
git clone git@github.com:bentoml/BentoML.git
pip install -r ./bentoml/guides/quick-start/requirements.txt
python ./bentoml/guides/quick-start/main.py

bentoml containerize IrisClassifier:latest -t iris-classifier

docker run -v $(PWD):/data iris-classifier:20200923110808_241FF4 bentoml run /bento predict --input-file=/data/test.csv
```

It works but it's quite cumbersome for a user to set up the docker environment and figure out mounting local files to the docker container etc.

**Describe the solution you'd like**

BentoML should provide a more convenient way for the user to do this via one CLI command, e.g.:

```bash
$ bentoml run IrisClassifier:latest predict --input-file=./test.csv --format=csv --with-docker
```
Which should automatically build a docker image and start a docker container to run an inference job with the specified input data

**Describe alternatives you've considered**

Suggestions for alternatives are welcomed

**Additional context**

N/A

**Comment by jackyzha0** [comment]
To me, it's not obvious that `--with-docker` will also build the image as well. Maybe adding a `--build` flag to make the Docker build step optional so it just does the docker run part? If the flag isn't included we should look for an existing Docker image and if it doesn't exist, throw a warning.

**Comment by parano** [comment]
@jackyzha0  I think it's ok to just always build the docker image and users don't need to provide this extra argument. Note that if the docker image has been built before even with a different tag, docker build should just use the cached layers and the build will be very fast.

**Comment by iancoffey** [comment]
As a bit of an aside- Ive also run into an issue where most of the environments I want to build BentoML services will not have Docker running, so I am working on [this small helper](https://github.com/iancoffey/bentoml-builder) to create K8s Jobs or Tekton Tasks automatically - https://github.com/iancoffey/bentoml-builder

**Comment by Trollgeir** [comment]
Could I suggest that this can be executed with an argument passed directly to the image, leaving the BentoML CLI as a wrapper for the image args?

I like the idea of the image to not only be a serving model, but also a function which you can apply on a csv/parquet/json file. After all, this is a subset of the serving module's functionalities.

The reason for this is because it's extremely handy workflow frameworks such as Argo to pass in the input artifact, execute the image with `args` such as `--predict -i input.parquet -o output.parquet`. If I were to implement this as is - would possibly have to inject a custom python script into the image to do something equivalent.

**Comment by gregd33** [comment]
I mentioned this on slack, but something I found out the hard way: when using the batch processing,  the command to the docker file needs to be called via a shell comment (e.g. `sh -c 'bentoml run /bento predict --input-file /data/images/*.png -q'`) since the `*` will not parse properly otherwise. Just wanted to mention it here.

**Comment by parano** [comment]
Thanks for sharing @gregd33

I think with the new inference jobs API proposal that we are working on, this proposal with `--with-docker` option no longer makes sense, closing this issue now and we will make sure to address this issue in the new design.
