### ISSUE TITLE
Why does JsonInput put the JSON into a list? 

### ISSUE THREAD

**Issue by thejaminator** [bentoml/BentoML#1206]
**Describe the bug**
Given the request
```
curl --request POST \
  --url http://localhost:5000/predict_batch \
  --header 'content-type: application/json' \
  --data '{"text":"sdfsafdf"}'
```

Following the documentation
```
    @api(input=JsonInput(), batch=True)
    def predict_batch(self, parsed_json_list: List[JsonSerializable], tasks: List[InferenceTask]):
        print(parsed_json_list) # [{'text': 'sdfsafdf'}] instead of {'text': 'sdfsafdf'}?
        model_input = []
        for json, task in zip(parsed_json_list, tasks):
            if "text" in json:
                model_input.append(json['text'])
            else:
                task.discard(http_status=400, err_msg="input json must contain `text` field")

        return model_input
```

Tthe input ` {'text': 'sdfsafdf'}` becomes a list, resulting in `[{'text': 'sdfsafdf'}]`.
Is this behaviour intended? 
I want to pass a JSON array of dictionaries for batch processing - e.g. [{"text":"sdfsafdf"},{"text":"sdfsafdf"}].
But this behaviour lifts the list into a list of lists - [[{"text":"sdfsafdf"},{"text":"sdfsafdf"}]].

**To Reproduce**

**Expected behavior**

Expected the parsed json to simply be a single JSON object

**Screenshots/Logs**

**Environment:**
 - OS: [MacOS 10.15.7]
 - Python Version [ Python 3.8.5]
 - BentoML Version [BentoML==0.9.2]

**Comment by yubozhao** [comment]
@thejaminator When the batch mode turns on, `batch=True`, the requests will automatically batch together in to a list and provided to the API function. If throughput is a concern, I recommend to have batch mode turns on.

If throughput is not a hugely concern, you have have batch mode turn off, and the input will be `JSON` instead of `List(JSON)`.

You can find more information about batch option at the documentation: https://docs.bentoml.org/en/latest/concepts.html#defining-a-batch-api

If you still see a list of JSON when you have batch mode off, let me know and I will look into it.

**Comment by thejaminator** [comment]
Thanks @yubozhao . I misunderstood what batch=True was doing (automatically batching together).

I was passing an Array of JSON objects to the API manually myself. 

Switching to batch=False fixed the project

**Comment by yubozhao** [comment]
Yeah, we should help users to have more clear understanding for `batch`.  Welcome any ideas that can improve that!
