### ISSUE TITLE
Prometheus metrics endpoint isn't loaded properly 

### ISSUE THREAD

**Issue by danield137** [bentoml/BentoML#1218]
**Describe the bug**
In some scenarios, when debugging locally, the bento related metrics are not returned properly from the `/metrics` endpoint.

**To Reproduce**
Running locally using:

https://gist.github.com/danield137/d54fdf218c4f39c50fbd9289ca79cf6c#file-start_local-py

Going to: `localhost:5000/metrics`, I don't see `BENTO_` prefixed metrics.

**Environment:**
 - OS: MacOs
 - Python 3.8
 - BentoML 0.9.2

**Additional context**
I think this traces back to the way the view is generated.

It seems to be generated differently for `gunicorn` and vanilla.
The [gunicorn version](https://github.com/bentoml/BentoML/blob/b068b5f56ab9059645660c0536fe6adee149b175/bentoml/server/gunicorn_server.py#L39) passes the specific registry, whereas the [regular one](https://github.com/bentoml/BentoML/blob/b875912dd377e8411d6698f504a20d31cca5e091/bentoml/server/api_server.py#L177) doesn't, which falls back to the singleton `REGISTRY`.

When I changed [this line](https://github.com/bentoml/BentoML/blob/fbcd691d3ad6baf009c20c656b1cad2beb0a4cb1/bentoml/server/instruments.py#L17) to use the singleton registry, 

`from prometheus_client import Histogram, Counter, Gauge, REGISTRY`

It worked properly.

I assume there is a good reason for creating a new registry, as such, perhaps the missing piece of code is just passing the correct registry from the metrics middleware [here](https://github.com/bentoml/BentoML/blob/b875912dd377e8411d6698f504a20d31cca5e091/bentoml/server/api_server.py#L177)

**Comment by parano** [comment]
I tested this locally and it seems the "/metrics" page is not showing any metrics information when using the development mode `bentoml serve`.  Production workloads running with `bentoml serve-gunicorn` should not be affected tho. 

The API server is using a local registry instead of the global one because of potential race condition when running with Gunicorn. Same reason why we are using the multiple processor collector: https://github.com/bentoml/BentoML/blob/v0.9.2/bentoml/server/gunicorn_server.py#L29
