### ISSUE TITLE
Update all validation from using Cerberus library to schema library

### ISSUE THREAD

**Issue by yubozhao** [bentoml/BentoML#1505]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aarnphm** [comment]
Is this the library we want to migrate to https://github.com/keleshev/schema?

**Comment by yubozhao** [comment]
Yes. This is the library.  We might hold off to this issue until we updated the deployments workflow

**Comment by aarnphm** [comment]
``schema`` seems like a simplified ``cerberus``. We can achieve custom validator in Cerberus customization with ``Hook``, and their API seems to be a lot user friendly than ``cerberus``. 

Just my preference, I would like to use ``cerberus`` over ``schema`` since cerberus API is a lot more powerful in term of customization. On the other hand, It will take devs a lot more efforts to learn and understand cerberus API in order to create  a customized data validator. 

I agree that if we only validate our deployment proto then the switch to ``schema`` is reasonable. Do we have any other use-case for data validation elsewhere that we might want to implement ?

**Comment by larme** [comment]
During today's discussion we also briefly mentioned [pydantic](https://github.com/samuelcolvin/pydantic) as a possible option.

**Comment by aarnphm** [comment]
This is not relevant anymore :)
