### ISSUE TITLE
Deploy Yatai By remote db and local path report  can't locate config file 'bentoml.yml' 

### ISSUE THREAD

**Issue by wuxutao** [bentoml/BentoML#1796]
**Describe the bug**
 I deploy Yatai Service by a remote PostgreSQL database and local repo base,  
When I use command:  bentoml containerize IrisClassifier:latest -t iris-classifier  --yatai-url=127.0.0.1:50051 
It report error:  Error: bentoml-cli containerize failed: BentoML can't locate config file 'bentoml.yml' in saved bundle in path: /bentoml/repository/IrisClassifier/20210803122208_2E7460

But the file "bentoml.yml" is in the docker volume

**To Reproduce**

1. Start Yaitai service: "docker run -p 3000:3000 -p 50051:50051     -v ~/bentoml:/bentoml   bentoml/yatai-service:latest    --db-url postgresql://postgres:postgres@192.168.0.47:15433/wt     --repo-base-url /bentoml/repository"
2. # Save Bento bundle to Yatai server
bento_svc.save(yatai_url="127.0.0.1:50051")
3. bentoml containerize IrisClassifier:latest --yatai-url=127.0.0.1:50051

It will report error

![image](https://user-images.githubusercontent.com/2825910/127980581-d8451bdc-a885-47ff-a8b3-0ae42eca1879.png)

and what  is "api.amplitude.com"?

**Comment by mqk** [comment]
I also see this same error. In my setup I deployed the yatai service on kubernetes (minikube).
```
$ bentoml containerize --yatai-url http://127.0.0.1:62838 IrisClassifier:latest
Found Bento: /root/bentoml/repository/IrisClassifier/20210823162836_FDA855
Error: bentoml-cli containerize failed: BentoML can't locate config file 'bentoml.yml' in saved bundle in path: /root/bentoml/repository/IrisClassifier/20210823162836_FDA855
```

**Comment by parano** [comment]
Hi @wuxutao @mqk - sorry about the delay in getting back to you. The reason for this issue is that in BentoML 0.13, Yatai requires a storage backend for storing the Models and it supports both local file system and blob storage(AWS S3, MinIO, Azure blob storage). However, when Yatai is deployed in production mode and connected remotely, only blob storage is supported. Local storage is only meant for local Yatai only. This is definitely something we should document better.

Note that BentoML 1.0 and new Yatai project are around the corner. In the new Yatai, we only support blob storage as the model/bento storage backend, however setting up Yatai on kubernetes will be a lot easier via Helm, where it will automatically create an MinIO instance in the cluster for storage by default.
