### ISSUE TITLE
memory sharing for the same artifact to reduce the total amount of memory required when using many workers

### ISSUE THREAD

**Issue by withsmilo** [bentoml/BentoML#1866]
**Is your feature request related to a problem? Please describe.**

When we use many workers to serve the same model in one pod, we have a problem of using redundant memory per worker for the same artifact. Can each worker share the same artifact?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by parano** [comment]
@withsmilo really glad you brought up this issue, the upcoming 1.0 release will address exactly this, models will be placed in a separate process shared by multiple API server workers, via a concept called [Runner](https://github.com/bentoml/BentoML/blob/35b7dd5b8b66bfd3d54d6f57a863f27161667991/bentoml/_internal/service/runner.py#L153). We will provider Runner implementation for most ML frameworks and allow users to define custom Runner implementation.

**Comment by withsmilo** [comment]
@parano 
Thanks for sharing! It's great news. :)

**Comment by withsmilo** [comment]
@parano 
As workaround for BentoML v0.13.1, we turned on the `preload_app` option of Gunicorn to resolve this problem.
```python
self.options = {
                "bind": self.bind,
                "preload_app": True,  # <--- ADDED!
                "timeout": timeout,  # TODO
                "limit_request_line": max_request_size,
                "loglevel": loglevel.upper(),
            }
```
> https://github.com/bentoml/BentoML/blob/v0.13.1/bentoml/server/gunicorn_server.py#L98-L103

**Comment by parano** [comment]
Update: this feature is now supported in the upcoming 1.0 version. BentoML 1.0 provide a Runner concept which contains a unit of IO or Compute intense program, and it allow users to customize how to scale base on resources available. A pre-built Runner class will also be provided for all common ML frameworks, which is optimized for the framework's own performance characteristic, in order to achieve higher performance and better resource utilization. As an example, XGBoost Runner will have only one replica in memory, shared by multiple API server instances, and `run` calls to the Runner will be batched: https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/xgboost.py
