### ISSUE TITLE
"ImportError: No module named" when packing Bento service from library

### ISSUE THREAD

**Issue by Meosit** [bentoml/BentoML#1951]
**Describe the bug**

We have a library which contains a predefined BentoML service and have a few local dependencies in it. This library have a method which performs a bento service pack + save methods (over provided models). The issue is that saved BentoML bundle contains the service class itself, but not it's dependencies, which in turn cause a model name import collision (service class cannot import library dependencies because it has the same module name)

**To Reproduce**
1. Download example [bentoml-bug-reproduce.zip](https://github.com/bentoml/BentoML/files/7462600/bentoml-bug-reproduce.zip)
2. Install and activate conda environment
3. Go to `a-library` folder
4. run `python setup.py bdist_wheel` (or you can run `python setup.py install` which will cause some other strange bug while packing)
5. run `pip install dist/a_library-0.0.1-py3-none-any.whl`
6. Go to `a-project/a_project` folder
7. Run `python main.py`

**Expected behavior**
This depends, I see three options:
- Modify the bundle to be able to run service which lays inside a library
- Modify the import package which causes a collision
- Handle this case and copy all of the local dependencies directly from library (as it done for service class)

**Environment:**
 - OS: `MacOS 11.6`
 - Python Version `3.7` (but reproducible on other versions)
 - BentoML Version `0.13.1`

**Additional context**
This is happened [on this line](https://github.com/bentoml/BentoML/blob/v0.13.1/bentoml/saved_bundle/bundler.py#L105) and specifically [here](https://github.com/bentoml/BentoML/blob/v0.13.1/bentoml/saved_bundle/pip_pkg.py#L165). Since the bento service class file **always copied**, but it's local dependencies are ignored (they are local relative to bento service class, but a lib dependency relative to a user code). 

This can be fixed in a different ways, so I'm not sure which is the best one or maybe I'm missing something.

**Workaround**
If there is an access to the library code, then the service class file itself can be moved in a completely different module in order to dodge the module name collision

**Comment by aarnphm** [comment]
HI @Meosit, have you tried adding the dependencies as a `zipimport` into https://docs.bentoml.org/en/latest/api/bentoml.html?highlight=env#env zipimport?

**Comment by Meosit** [comment]
Hi @aarnphm, only in the example I used a local package to make it self-contained, but this is also reproducible with pip packages. As I mentioned, the packages itself are added correctly and as expected, the issue is with the bundler and with code which copied inside the bundle

**Comment by parano** [comment]
Hi @Meosit - this issue should be fixed in the upcoming BentoML 1.0 release. In BentoML 1.0, a project root must be specifically defined by placing a bentofile.yaml file in the directory. This file specifies all the Bento build configs, including what are the files to include in the final Bento built. The project root also should be seen as the CWD in your service's python environment, as well as part of the import path in sys.path. A more detailed explanation can be found here: https://github.com/bentoml/BentoML/tree/main/bentoml/_internal/bento

That being said, when creating a Bento from an existing Python application or library, you must make sure the python instance's CWD is set to the project root of your BentoML project. Alternatively, you can use something like `subprocess.check_output` to run `bentoml build` command from the BentoML project directory.
