### ISSUE TITLE
error in iris classifier example

### ISSUE THREAD

**Issue by lililigithub** [bentoml/BentoML#221]
**Describe the bug**

**To Reproduce**
1. start jupyter notebook locally on Mac
2. follow example here and it will fail, as shown in the screenshot

**Expected behavior**
it shouldn't error out

**Screenshots/Logs**
If applicable, add screenshots, logs or error outputs to help explain your problem.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/52649479/61671363-2b217780-ac9c-11e9-8415-95d3db5aa716.png">

**Environment:**
 - Python/BentoML Version [e.g. Python 2.7, BentoML-0.2.0]

**Additional context**

**Comment by parano** [comment]
Thanks for reporting this @lililigithub, this was a regression in BentoML 0.2.0 with python 2. It was due to the naming of the `utils/logging.py` module, which we renamed in 0.3.0: https://github.com/bentoml/BentoML/commit/2b65b0f64633b20fb932c0656fecbfdd41f32542#diff-487f064cd0b1801de81de636a925a0fb 

Upgrading to 0.3.0 or using 0.2.0 with python3 should work:
```
pip install -U bentoml
```

**Comment by lililigithub** [comment]
Thanks @parano !

I'm closing this issue.
