### ISSUE TITLE
bentoml.load() changes the working directory

### ISSUE THREAD

**Issue by mqk** [bentoml/BentoML#2263]
**Describe the bug**
The act of loading a bento service changes the user's working directory.

**To Reproduce**
```
In [1]: import os, bentoml
   ...: 
   ...: cwd = os.getcwd()
   ...: bento_service = bentoml.load("galapagos:latest")
   ...: print(cwd)
   ...: print(os.getcwd())
[11:34:52] INFO     Service loaded from Bento store: bentoml.Service(tag="galapagos:nmc24zuk7sryhlg6", path="/Users/mike.kuhlen/bentoml/bentos/galapagos/nmc24zuk7sryhlg6")                                                
/Users/mike.kuhlen
/Users/mike.kuhlen/bentoml/bentos/galapagos/nmc24zuk7sryhlg6/src
```

**Expected behavior**
I would expect to end up in the same directory as before the call to `bentoml.load`.

**Environment:**
 - OS: [e.g. MacOS 10.14.3]: 11.6.1
 - Python Version [e.g. Python 3.7.1]: 3.8.8
 - BentoML Version [e.g. BentoML-0.8.6]: 1.0.0a3

**Comment by parano** [comment]
Hi @mqk - this is currently an expected behavior in 1.0. Setting CWD is not about loading the service code actually(for that we simply insert bento path to sys.path). Changing CWD is meant to allow user service or API code to read files using relative file path, from the project directory, e.g. `open('./config.yaml')`. This means we can't reset the CWD back after `load`, because reading file may happen later when the API function is invoked.

I agree this is a very confusing behavior especially when using `bentoml.load` form an interactive shell or notebook. We've been considering exactly what you suggested, however, that means all user code that read local file, must be using file path relative to the current file, something like:

```python
current_folder_path = os.path.dirname(os.path.realpath(__file__))
open(os.path.join(current_folder_path, "config.yaml"))
```

I'm curious what's your preference on this design choice? @mqk

**Comment by mqk** [comment]
I see. Personally, I find it a bit odd to support loading of local files from a relative path, but maybe there's a good reason for that. Just to make sure I'm understanding it correctly: some users define a bento service that loads resources from disk, and they have an expectation that the current-working-directory is the bento's `src/` directory? I can't really speak to the validity of that expectation, but I do know that it's pretty confusing and non-standard behavior to have a side effect of changing the cwd on calling a `.load()` method.

**Comment by parano** [comment]
Thank you again for the feedback @mqk - after more discussion with the team, we all agree with your view and decided to make the change, we will follow up with a PR to fix this behavior.

**Comment by parano** [comment]
Current proposal:

We will add an additional parameter `set_bento_working_dir` to load:

```bash
bentoml.load('my_svc:latest', set_bento_working_dir=True)
```

The default value for `set_bento_working_dir` will be false, so for users using `bentoml.load` in an interactive setting, they won't get confused by the cwd changing behavior. While for BentoML CLI commands like `bentoml serve`, internally it will set the `set_bento_working_dir=True`, so all the reading files behaviors are consistent as it is running from a project directory during development.
