### ISSUE TITLE
feature: Change the way Dynamic Batching is used

### ISSUE THREAD

**Issue by nextauthn** [bentoml/BentoML#2923]
### Feature request

I tested the queue has a performance impact, you can consider using shared memory for Dynamic Batching. python 3.8 supports shared memory.

**Comment by yubozhao** [comment]
@nextauthn can you elaborate more?  I would like to learn your tests and see how we can improve. @larme

**Comment by sauyon** [comment]
BentoML is intentionally architected with RPCs in the middle so that the frontend and backend components can be scaled separately in a cloud environment.

That said, if latency is a prime concern, we now have [embedded runners](https://docs.bentoml.org/en/latest/integrations/flink.html#embedded-model-runners)!
