### ISSUE TITLE
InputAdapter for Image file plus additional JSON data

### ISSUE THREAD

**Issue by ecrows** [bentoml/BentoML#934]
**Is your feature request related to a problem? Please describe.**
A common use-case for models that take image input is to also include additional information about the image (such as object detection bounding boxes, segmentation masks, class labels, face keypoints, etc.)  To my knowledge, ImageInput does not allow you to include this kind of information by default.

**Describe the solution you'd like**
 It would be very useful to have an optional keyword argument to ImageInput that specifically allows for a JSON containing image metadata or annotation information to be included.  This would be a non-breaking change.  (Alternatively, some mechanism to provide multiple input adapters in the @bentoml.api decorator would help with this, but would likely create a lot more complexity.)

**Describe alternatives you've considered**
Currently, to include this information, I am using a custom input adapter that handles arbitrary binary files via input_names (which isn't very tidy).  I'm considering writing a new subclass of ImageInput to have a more developer-friendly solution that can be re-used for several services and is more tailored to this common use-case, but it feels like this could be included by default in ImageInput without adding much complexity, while reducing the need for others to write custom adapters.

Seeing as I'm already planning on doing something similar, I'd be open to provide an implementation (if this seems like something we want to have in the official ImageInput implementation).

**Comment by parano** [comment]
Hi @ecrows - thanks for the feature request, this is definitely one of the most asked features in the slack channel. I've told many users the workaround: to use a JSON input adapter and use base64 to encode their image file in a JSON field along with other information for inferencing. A more developer-friendly option would definitely be preferred if you are interested in contributing.

Could you share a bit more about how you plan to implement it?  I'm curious what is the experience when writing the API client-side code. Does it still require the client to base64 encode the image file?

**Comment by ecrows** [comment]
Thanks for the quick reply!

I'm thinking of adding an `accept_json=False` argument to __init__ in imageInput.  If this argument is set to True in the decorator call, a property called "json_file" is added to the request schema, with `required: False`.  Then, if the user sends a "json_file" object along with their request, the data will be parsed in a similar manner to JsonInput, and passed as an argument to the user's "predict" function (or similar).

Are we planning on supporting batch inputs with ImageInput?  There's currently a "handle_batch_request" function (and BATCH_MODE_SUPPORTED = True on line 81) in the class, but setting `is_batch_input=True` causes a hardcoded ValueError during __init__.  Only reason I'm wondering is because that may make a difference as to how to handle batch image+JSON requests in CLI mode.

**Comment by parano** [comment]
Hi @ecrows - great questions about batching support. Sorry those things are not well documented right now.

`is_batch_input=True` means whether or not a client can send multiple inference requests within one HTTP request call.  Some input adapters support that and some does not. ImageInput for example only supports client sending one request at a time.

`handle_batch_request ` is used when micro-batching feature is enabled. It is a performance optimization feature that drastically improves the overall server throughput by batching API requests into small batches in real-time.  Users can enable it by pass `--enable-microbatch` to API server docker or CLI command. The ImageInput already supports micro-batching, with its `handle_batch_request` method implementation.

I'd recommend adding a separate input adapter instead of adding a parameter to the existing ImageInput class. This is mostly because the existing image input supports both content type `multipart/form-data` and `image/*`. Where in your proposal, it seems it only supports `multipart/form-data`. I slightly prefer to make ImageInput simpler and works well for simple use cases where one single image is used as inference input without dealing with or thinking about parameters they may not need.  The recent MultiImageInput #806 is a really good example. It gives advanced users an option to use multiple images as one inference input, without introducing complexity to the simple ImageInput's implementation.

**Comment by ecrows** [comment]
Ah, thanks for the extra context on batching, that makes sense to me now.  Also a good point regarding ImageInput `image/*` content type.  I'll put together a custom adapter and report back soon.

**Comment by ecrows** [comment]
🥳
