### ISSUE TITLE
Allow returning HTTP response from services API endpoints

### ISSUE THREAD

**Issue by co42** [bentoml/BentoML#936]
**Is your feature request related to a problem? Please describe.**
I want to return a custom HTTP response (and code) from an API endpoint. It allows to handle errors gracefully for example.

**Describe the solution you'd like**
I modified `JsonSerializableOutput` to forward `SimpleResponse` like so https://github.com/bentoml/BentoML/compare/master...co42:feature/json-output-http-response

Now I can do :
```python
    @bentoml.api(input=JsonInput(), output=JsonSerializableOutput())
    def predict(self, input_data):
        if something_wrong:
            return SimpleResponse(400, (('Content-Type', 'application/json'), ), json.dumps({'error': 'Something wrong'}))
        # ...
```

**Describe alternatives you've considered**
Maybe raise a custom exception. Is there a way to make it work without modifying every output handlers ?

**Comment by parano** [comment]
Hi @co42,

BentoML is designed to not only work for model serving over an API HTTP endpoint, but also serving via CLI command, python API, and batch serving on Apache Spark. That's why returning a SimpleResponse directly is not currently supported. Raising a custom exception is the right way to go. I think `bentoml.exceptions.InvalidArgument` is what you are looking for.  It should work when micro-batching is not enabled(which is the default right now). We are working on better ways to do error handling when micro-batching is enabled.

**Comment by co42** [comment]
`bentoml.exceptions.InvalidArgument` was exactly what I was looking for. Thanks
